name: Bug Report
description: Report a reproducible bug or regression.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report.
        Please provide enough detail for us to reproduce and fix quickly.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List exact steps, including commands/configuration if relevant.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Impacted Area
      options:
        - Plugin
        - Server API
        - Admin Console
        - Docs
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include OS, Node.js version, and relevant deployment details.
      placeholder: macOS 15, Node 20.18, Docker Desktop 4.x, etc.

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste logs, stack traces, or screenshots.
      render: shell

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I removed sensitive data from logs and screenshots.
          required: true
